apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: stock-app
data:
  grafana.ini: |
    [smtp]
    enabled = true
    host = smtp.gmail.com:587
    user = rm955069@gmail.com
    password = fvanncxwvtnmmysu
    skip_verify = true
    from_address = rm955069@gmail.com
    from_name = Grafana
    ehlo_identity = grafana.example.com
