apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: stock-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: {{ .Values.backend.image }}
          env:
            {{- range $key, $value := .Values.backend.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: stock-app
spec:
  type: NodePort
  ports:
    - port: 8000
      nodePort: {{ .Values.backend.nodePort }}
  selector:
    app: backend
