apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: stock-app
data:
  grafana.ini: |
    [smtp]
    enabled = {{ .Values.grafana.smtp.enabled }}
    host = {{ .Values.grafana.smtp.host }}
    user = {{ .Values.grafana.smtp.user }}
    password = {{ .Values.grafana.smtp.password }}
    skip_verify = {{ .Values.grafana.smtp.skip_verify }}
    from_address = {{ .Values.grafana.smtp.from_address }}
    from_name = {{ .Values.grafana.smtp.from_name }}
    ehlo_identity = {{ .Values.grafana.smtp.ehlo_identity }}
