apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-collector
  namespace: stock-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metrics-collector
  template:
    metadata:
      labels:
        app: metrics-collector
    spec:
      containers:
        - name: metrics-collector
          image: {{ .Values.metricsCollector.image }}
          ports:
            - containerPort: 7878
---
apiVersion: v1
kind: Service
metadata:
  name: metrics-collector
  namespace: stock-app
spec:
  type: NodePort
  ports:
    - port: 7878
      nodePort: {{ .Values.metricsCollector.nodePort }}
  selector:
    app: metrics-collector
