apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: stock-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: postgres
          image: {{ .Values.postgres.image }}
          env:
            {{- range $key, $value := .Values.postgres.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: stock-app
spec:
  type: NodePort
  ports:
    - port: 5432
      nodePort: {{ .Values.postgres.nodePort }}
  selector:
    app: db
